# Welcome to Jekyll!
#

# Site settings
title: Leadomise
description: |
  Zintegrowany system informatyczny <br /> wykorzystujący metody sztucznej inteligencji <br /> do automatycznej optymalizacji kandydatów na nowe leki
owner: Politechnika Warszawska # or company name
email: k.kaminska@tele.pw.edu.pl
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://leadomise.com" # the base hostname & protocol for your site
social:
  #twitter: https://twitter.com/thervira
  #github: https://github.com/thervira
  #linkedin-square: https://linkedin.com/in/<username>
  #facebook-official: https://facebook.com/thervira
  #google-plus-square: https://plus.google.com/u/0/+<username>
  email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
